# Generated by Django 5.0 on 2023-12-26 13:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mango', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contact',
            old_name='decription',
            new_name='description',
        ),
    ]
